"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Member = { id: string; full_name: string };
type Document = { id: string; title: string; category: string; storage_path: string; mime_type: string; byte_size: number; document_date: string | null; is_archived: boolean; family_members: { full_name: string }[] };
type Caregiver = { caregiver_id: string; profiles: { display_name: string }[] };
const accepted = ["application/pdf", "image/jpeg", "image/png", "image/webp"];

export function DocumentsWorkspace({ householdId, members, documents, caregivers }: { householdId: string | null; members: Member[]; documents: Document[]; caregivers: Caregiver[] }) {
  const [filter, setFilter] = useState("all"); const [query, setQuery] = useState(""); const [file, setFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const filtered = useMemo(() => documents.filter(document => (filter === "all" || document.category === filter) && document.title.toLowerCase().includes(query.toLowerCase())), [documents, filter, query]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setMessage(null); if (!file || !householdId) return setError("Choose a supported file and create a household first."); if (!accepted.includes(file.type) || file.size > 10485760) return setError("Use a PDF, JPEG, PNG, or WebP file no larger than 10 MB."); const form = new FormData(event.currentTarget); const familyMemberId = String(form.get("family_member_id") || ""); if (!familyMemberId) return setError("Choose the family member this record belongs to."); setUploading(true); const id = crypto.randomUUID(); const filename = file.name.replace(/[^a-zA-Z0-9._-]/g, "-").slice(-120); const storagePath = `${householdId}/${id}/${filename}`; const supabase = createClient(); const { error: uploadError } = await supabase.storage.from("medical-records").upload(storagePath, file, { contentType: file.type, upsert: false }); if (uploadError) { setUploading(false); return setError("The file could not be uploaded. Check your access and try again."); } const response = await fetch("/api/documents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, familyMemberId, category: form.get("category"), title: form.get("title"), storagePath, mimeType: file.type, byteSize: file.size, documentDate: form.get("document_date") || undefined, clinicianName: form.get("clinician_name") || undefined, notes: form.get("notes") || undefined }) }); if (!response.ok) { await supabase.storage.from("medical-records").remove([storagePath]); setUploading(false); return setError("The file was removed because its record could not be saved."); } setMessage("Document uploaded to your private vault."); setFile(null); (event.target as HTMLFormElement).reset(); setUploading(false); window.location.reload(); }
  async function openDocument(document: Document) { setError(null); const supabase = createClient(); const { data, error: signedError } = await supabase.storage.from("medical-records").createSignedUrl(document.storage_path, 60); if (signedError || !data?.signedUrl) return setError("A secure preview link could not be created."); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  async function updateDocument(id: string, method: "PATCH" | "DELETE", archived?: boolean) { setError(null); const response = await fetch(method === "DELETE" ? `/api/documents?id=${id}` : "/api/documents", { method, headers: { "Content-Type": "application/json" }, body: method === "PATCH" ? JSON.stringify({ id, archived }) : undefined }); if (!response.ok) return setError("Document update failed. Please try again."); window.location.reload(); }
  async function setCaregiverConsent(documentId: string, caregiverId: string, revoke = false) { setError(null); const response = await fetch("/api/document-consents", { method: revoke ? "DELETE" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ documentId, caregiverId }) }); if (!response.ok) return setError("Caregiver document consent could not be updated."); setMessage(revoke ? "Caregiver document access revoked." : "Caregiver may now view this document through a secure link."); }
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 border-b border-[#e1eae2] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/app" className="text-sm font-bold text-[#27815b]">← Back to CareLoop</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-[#4d9c73]">Private records vault</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#19332f]">Documents</h1><p className="mt-2 text-sm text-[#688077]">Store medical records in a private bucket; documents are never public.</p></div></div>
    <section className="soft-card mt-6 rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Upload a record</h2><p className="mt-1 text-xs text-[#71877f]">PDF, JPEG, PNG, or WebP · maximum 10 MB</p><form onSubmit={upload} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Family member<select required name="family_member_id" className="mt-1.5 w-full rounded-xl border border-[#dce7df] bg-white p-3 text-sm font-normal"><option value="">Select a profile</option>{members.map(member => <option key={member.id} value={member.id}>{member.full_name}</option>)}</select></label><label className="text-sm font-bold">Category<select name="category" className="mt-1.5 w-full rounded-xl border border-[#dce7df] bg-white p-3 text-sm font-normal"><option value="prescription">Prescription</option><option value="lab_report">Lab report</option><option value="imaging">Imaging & scan</option><option value="vaccination">Vaccination</option><option value="insurance">Insurance</option><option value="other">Other record</option></select></label><Field name="title" label="Title" placeholder="Annual blood work" required/><Field name="document_date" label="Document date" type="date"/><Field name="clinician_name" label="Doctor or clinic"/><label className="text-sm font-bold">File<input required type="file" accept=".pdf,image/jpeg,image/png,image/webp" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} className="mt-1.5 block w-full text-xs font-normal"/></label><label className="sm:col-span-2 text-sm font-bold">Notes<textarea name="notes" rows={2} className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal"/></label><div className="sm:col-span-2">{error && <p role="alert" className="rounded-xl bg-[#fff0ec] px-3 py-2.5 text-xs text-[#a14f3b]">{error}</p>}{message && <p role="status" className="rounded-xl bg-[#eaf6ed] px-3 py-2.5 text-xs text-[#23724e]">{message}</p>}<button disabled={uploading || !householdId || members.length === 0} className="mt-3 rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{uploading ? "Uploading…" : "Upload securely"}</button></div></form></section>
    <div className="mt-6 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search records" className="rounded-xl border border-[#dce7df] bg-white px-3 py-2.5 text-sm outline-none sm:w-64"/><div className="flex flex-wrap gap-2">{[["all","All records"],["prescription","Prescriptions"],["lab_report","Lab reports"],["imaging","Imaging"],["vaccination","Vaccinations"],["insurance","Insurance"]].map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-2 text-xs font-bold ${filter === value ? "bg-[#1b7152] text-white" : "border border-[#dce7df] bg-white text-[#607a70]"}`}>{label}</button>)}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-[#cbded0] bg-white p-10 text-center sm:col-span-2 lg:col-span-3"><p className="text-sm font-bold">No matching records</p><p className="mt-1 text-xs text-[#71877f]">Upload a record or use a different filter.</p></div> : filtered.map(document => <DocumentCard key={document.id} document={document} caregivers={caregivers} openDocument={openDocument} updateDocument={updateDocument} setCaregiverConsent={setCaregiverConsent}/>)}</div><p className="mt-6 rounded-2xl bg-[#edf7ef] p-4 text-[11px] leading-5 text-[#638474]">Caregivers cannot view records unless a household owner explicitly grants access to a specific document. Files remain private and are served only through short-lived signed links.</p></main>;
}
function DocumentCard({document,caregivers,openDocument,updateDocument,setCaregiverConsent}:{document:Document;caregivers:Caregiver[];openDocument:(d:Document)=>void;updateDocument:(id:string,method:"PATCH"|"DELETE",archived?:boolean)=>void;setCaregiverConsent:(documentId:string,caregiverId:string,revoke?:boolean)=>void}) { const [caregiverId,setCaregiverId]=useState(""); return <article className="soft-card rounded-3xl border border-[#e5ece6] bg-white p-4"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8f2fc] text-[#4e76ad]">▤</span>{document.is_archived && <span className="rounded-full bg-[#f4f0eb] px-2 py-1 text-[10px] font-bold text-[#887262]">Archived</span>}</div><h2 className="mt-6 truncate font-bold text-[#25443d]">{document.title}</h2><p className="mt-1 text-xs text-[#71877f]">{document.category.replace("_", " ")} · {document.family_members[0]?.full_name ?? "Family member"}</p><p className="mt-2 text-[11px] text-[#84978f]">{Math.ceil(document.byte_size / 1024)} KB{document.document_date ? ` · ${document.document_date}` : ""}</p><div className="mt-4 flex flex-wrap gap-2 border-t border-[#edf1ed] pt-3"><button onClick={() => openDocument(document)} className="text-xs font-bold text-[#27815b]">Preview / download</button><button onClick={() => updateDocument(document.id, "PATCH", !document.is_archived)} className="text-xs font-bold text-[#668078]">{document.is_archived ? "Restore" : "Archive"}</button><button onClick={() => updateDocument(document.id, "DELETE")} className="text-xs font-bold text-[#bd6048]">Delete</button></div>{caregivers.length > 0 && <div className="mt-4 rounded-xl bg-[#f6f9f6] p-3"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[#648375]">Explicit caregiver consent</p><div className="mt-2 flex gap-2"><select value={caregiverId} onChange={event=>setCaregiverId(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-[#dce7df] bg-white px-2 py-1.5 text-xs"><option value="">Choose caregiver</option>{caregivers.map(caregiver=><option key={caregiver.caregiver_id} value={caregiver.caregiver_id}>{caregiver.profiles[0]?.display_name ?? "Caregiver"}</option>)}</select><button disabled={!caregiverId} onClick={()=>setCaregiverConsent(document.id,caregiverId)} className="rounded-lg bg-[#e1f2e6] px-2 text-xs font-bold text-[#267251] disabled:opacity-50">Allow</button></div></div>}</article>; }
function Field({name,label,type="text",placeholder,required=false}:{name:string;label:string;type?:string;placeholder?:string;required?:boolean}) { return <label className="text-sm font-bold">{label}<input name={name} type={type} required={required} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal"/></label>; }
