"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { addFamilyMember, createHousehold, inviteCaregiver, revokeCaregiver, type FamilyState } from "@/app/app/family/actions";

type FamilyMember = { id: string; full_name: string; relationship: string; date_of_birth: string | null; blood_group: string | null; allergies: string | null; conditions: string | null };
type Caregiver = { caregiver_id: string; permission: string; granted_at: string; profiles: { display_name: string; email: string | null }[] };
type Activity = { id: string; action: string; occurred_at: string; details: Record<string, unknown>; profiles: { display_name: string }[] };
type Props = { household: { id: string; name: string } | null; members: FamilyMember[]; caregivers: Caregiver[]; activity: Activity[] };
const blankState: FamilyState = {};

export function FamilyWorkspace({ household, members, caregivers, activity }: Props) {
  const [showProfileForm, setShowProfileForm] = useState(false);
  const [householdState, householdAction, householdPending] = useActionState(createHousehold, blankState);
  const [profileState, profileAction, profilePending] = useActionState(addFamilyMember, blankState);
  const [inviteState, inviteAction, invitePending] = useActionState(inviteCaregiver, blankState);
  const [revokeState, revokeAction, revokePending] = useActionState(revokeCaregiver, blankState);

  if (!household) return <main className="mx-auto max-w-2xl px-4 py-12"><Link href="/app" className="text-sm font-bold text-[#27815b]">← Back to CareLoop</Link><section className="soft-card mt-6 rounded-3xl border border-[#e5ece6] bg-white p-6 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#4d9c73]">Your private space</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#19332f]">Create your household</h1><p className="mt-3 max-w-lg text-sm leading-6 text-[#688077]">A household is the private boundary around your family’s care information. You’ll be its owner and can later share specific access with a caregiver.</p><form action={householdAction} className="mt-7 max-w-md space-y-4"><label htmlFor="household-name" className="block text-sm font-bold text-[#25443d]">Household name</label><input id="household-name" name="name" required maxLength={120} placeholder="The Khan family" className="w-full rounded-xl border border-[#dce7df] px-3.5 py-3 text-sm outline-none focus:border-[#56a979] focus:ring-3 focus:ring-[#dff2e6]" /> <Status state={householdState}/><button disabled={householdPending} className="rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{householdPending ? "Creating…" : "Create household"}</button></form></section></main>;

  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 border-b border-[#e1eae2] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/app" className="text-sm font-bold text-[#27815b]">← Back to CareLoop</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-[#4d9c73]">{household.name}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#19332f]">Family & caregiver access</h1><p className="mt-2 text-sm text-[#688077]">Manage profiles and share only the access each caregiver needs.</p></div><button onClick={() => setShowProfileForm(!showProfileForm)} className="rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-semibold text-white">{showProfileForm ? "Close form" : "+ Add family member"}</button></div>
    {showProfileForm && <section className="soft-card mt-6 rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold text-[#19332f]">New family profile</h2><p className="mt-1 text-xs text-[#71877f]">Only add information you’re authorized to manage.</p><form action={profileAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Full name" name="full_name" required/><Field label="Relationship" name="relationship" placeholder="Child, parent, spouse…" required/><Field label="Date of birth" name="date_of_birth" type="date"/><Field label="Blood group" name="blood_group" placeholder="Optional"/><TextField label="Allergies" name="allergies"/><TextField label="Conditions" name="conditions"/><TextField label="Insurance notes" name="insurance_notes"/><TextField label="Basic health notes" name="health_notes"/><div className="sm:col-span-2"><Status state={profileState}/><button disabled={profilePending} className="mt-2 rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{profilePending ? "Saving…" : "Save profile"}</button></div></form></section>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="soft-card rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Family profiles</h2><p className="mt-1 text-xs text-[#71877f]">Health information stays inside this household.</p></div><span className="rounded-full bg-[#e8f4eb] px-2.5 py-1 text-xs font-bold text-[#27815b]">{members.length} profiles</span></div>{members.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-[#cbded0] bg-[#fbfdfb] p-8 text-center"><p className="text-sm font-bold text-[#25443d]">No family profiles yet</p><p className="mt-1 text-xs text-[#71877f]">Add yourself, a child, parent, spouse, or dependent to get started.</p></div> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{members.map(member => <article key={member.id} className="rounded-2xl border border-[#e5ece6] p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#d9eedf] text-xs font-bold text-[#236044]">{member.full_name.slice(0, 2).toUpperCase()}</span><h3 className="mt-4 font-bold text-[#25443d]">{member.full_name}</h3><p className="mt-1 text-xs text-[#71877f]">{member.relationship}{member.date_of_birth ? ` · Born ${member.date_of_birth}` : ""}</p><div className="mt-4 border-t border-[#edf1ed] pt-3 text-xs leading-5 text-[#607a70]"><p>Blood group: <span className="font-semibold">{member.blood_group ?? "Not recorded"}</span></p><p className="mt-1">Allergies: <span className="font-semibold">{member.allergies ?? "Not recorded"}</span></p></div></article>)}</div>}</section>
      <section className="soft-card rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Caregivers</h2><p className="mt-1 text-xs text-[#71877f]">Invite only people with a registered CareLoop account. Access can be revoked at any time.</p><form action={inviteAction} className="mt-5 grid gap-3 sm:grid-cols-[1fr_170px_auto]"><input name="email" required type="email" placeholder="caregiver@example.com" className="rounded-xl border border-[#dce7df] px-3 py-3 text-sm outline-none focus:border-[#56a979]"/><select name="permission" defaultValue="view" className="rounded-xl border border-[#dce7df] bg-white px-3 py-3 text-sm outline-none focus:border-[#56a979]"><option value="view">View only</option><option value="medicines">Manage medicines</option><option value="appointments">Manage appointments</option><option value="emergency">Emergency access</option><option value="full">Full caregiver access</option></select><button disabled={invitePending} className="rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">Invite</button></form><Status state={inviteState}/><div className="mt-5 divide-y divide-[#edf1ed]">{caregivers.length === 0 ? <p className="py-4 text-sm text-[#71877f]">No active caregivers yet.</p> : caregivers.map(caregiver => { const profile = caregiver.profiles[0]; return <div key={caregiver.caregiver_id} className="flex items-center gap-3 py-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e5edf9] text-xs font-bold text-[#4c74a7]">{profile?.display_name.slice(0, 2).toUpperCase() ?? "CG"}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{profile?.display_name ?? "Caregiver"}</p><p className="text-xs text-[#71877f]">{permissionLabel(caregiver.permission)}</p></div><form action={revokeAction}><input type="hidden" name="caregiver_id" value={caregiver.caregiver_id}/><button disabled={revokePending} className="text-xs font-bold text-[#b85e48]">Revoke</button></form></div>})}</div><Status state={revokeState}/></section></div>
      <aside className="soft-card h-fit rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Activity history</h2><p className="mt-1 text-xs text-[#71877f]">Important caregiver access actions.</p><div className="mt-5 space-y-4">{activity.length === 0 ? <p className="rounded-xl bg-[#f6f9f6] p-3 text-xs leading-5 text-[#71877f]">Activity will appear here when you invite, accept, or revoke caregiver access.</p> : activity.map(item => <div key={item.id} className="border-l-2 border-[#cce6d3] pl-3"><p className="text-xs font-bold text-[#25443d]">{formatAction(item.action)}</p><p className="mt-1 text-[11px] text-[#71877f]">{item.profiles[0]?.display_name ?? "A household member"} · {new Date(item.occurred_at).toLocaleDateString()}</p></div>)}</div><p className="mt-6 rounded-xl bg-[#edf7ef] p-3 text-[11px] leading-5 text-[#638474]">Permissions are enforced by database policies—not only the interface. Caregivers see only the household information their active permission allows.</p></aside></div></main>;
}

function Field({ label, name, type = "text", placeholder, required = false }: { label: string; name: string; type?: string; placeholder?: string; required?: boolean }) { return <label className="block text-sm font-semibold text-[#25443d]">{label}<input name={name} required={required} type={type} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-[#dce7df] px-3 py-3 text-sm font-normal outline-none focus:border-[#56a979]"/></label>; }
function TextField({ label, name }: { label: string; name: string }) { return <label className="block text-sm font-semibold text-[#25443d]">{label}<textarea name={name} rows={2} className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal outline-none focus:border-[#56a979]"/></label>; }
function Status({ state }: { state: FamilyState }) { return <>{state.error && <p role="alert" className="mt-3 rounded-xl bg-[#fff0ec] px-3 py-2.5 text-xs font-medium text-[#a14f3b]">{state.error}</p>}{state.message && <p role="status" className="mt-3 rounded-xl bg-[#eaf6ed] px-3 py-2.5 text-xs font-medium text-[#23724e]">{state.message}</p>}</>; }
function permissionLabel(permission: string) { return ({ view: "View only", medicines: "Manage medicines", appointments: "Manage appointments", emergency: "Emergency access", full: "Full caregiver access" } as Record<string, string>)[permission] ?? permission; }
function formatAction(action: string) { return ({ "caregiver.invited": "Caregiver invitation sent", "caregiver.accepted": "Caregiver access accepted", "caregiver.revoked": "Caregiver access revoked" } as Record<string, string>)[action] ?? action; }
