"use client";

import Link from "next/link";
import { useActionState } from "react";
import { initialSettingsState, updateNotifications, updateProfile, type SettingsState } from "@/app/app/settings/actions";

function Status({ state }: { state: SettingsState }) { return <>{state.error && <p role="alert" className="mt-3 rounded-xl bg-[#fff0ec] p-3 text-xs text-[#a14f3b]">{state.error}</p>}{state.message && <p role="status" className="mt-3 rounded-xl bg-[#eaf6ed] p-3 text-xs text-[#23724e]">{state.message}</p>}</>; }

export function SettingsWorkspace({ profile, preferences }: { profile: { display_name: string; email: string | null; timezone: string | null }; preferences: { medication_reminders: boolean; refill_alerts: boolean; appointment_reminders: boolean; timezone: string } | null }) {
  const [profileState, profileAction, profilePending] = useActionState(updateProfile, initialSettingsState);
  const [notificationState, notificationAction, notificationPending] = useActionState(updateNotifications, initialSettingsState);
  const timezone = preferences?.timezone ?? profile.timezone ?? "UTC";
  return <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><Link href="/app" className="text-sm font-bold text-[#27815b]">← Back to CareLoop</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-[#4d9c73]">Account & preferences</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#19332f]">Settings</h1><p className="mt-2 text-sm text-[#688077]">Update your profile and choose how CareLoop reminds you.</p>
    <div className="mt-6 space-y-6"><section className="soft-card rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Profile</h2><p className="mt-1 text-xs text-[#71877f]">Your email is managed securely through Supabase Auth.</p><form action={profileAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Display name<input name="display_name" defaultValue={profile.display_name} required className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal"/></label><label className="text-sm font-bold">Email<input value={profile.email ?? "Not available"} disabled className="mt-1.5 w-full rounded-xl border border-[#e6ece7] bg-[#f7f9f7] p-3 text-sm font-normal text-[#71877f]"/></label><label className="text-sm font-bold">Time zone<input name="timezone" defaultValue={profile.timezone ?? "UTC"} required className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal"/></label><div className="sm:col-span-2"><Status state={profileState}/><button disabled={profilePending} className="mt-2 rounded-xl bg-[#1b7152] px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{profilePending ? "Saving…" : "Save profile"}</button></div></form></section>
      <section className="soft-card rounded-3xl border border-[#e5ece6] bg-white p-5 sm:p-6"><h2 className="text-lg font-bold">Reminders</h2><p className="mt-1 text-xs text-[#71877f]">These settings control the reminders stored for your account. Delivery services can be enabled later without changing health records.</p><form action={notificationAction} className="mt-5 space-y-4"><Check name="medication_reminders" label="Medicine reminders" checked={preferences?.medication_reminders ?? true}/><Check name="refill_alerts" label="Refill alerts" checked={preferences?.refill_alerts ?? true}/><Check name="appointment_reminders" label="Appointment reminders" checked={preferences?.appointment_reminders ?? true}/><label className="block max-w-sm text-sm font-bold">Time zone<input name="timezone" defaultValue={timezone} required className="mt-1.5 w-full rounded-xl border border-[#dce7df] p-3 text-sm font-normal"/></label><Status state={notificationState}/><button disabled={notificationPending} className="rounded-xl border border-[#d7e4da] px-4 py-3 text-sm font-bold text-[#287354] disabled:opacity-60">{notificationPending ? "Saving…" : "Save reminder settings"}</button></form></section>
      <section className="rounded-3xl border border-[#f1d5ca] bg-[#fffaf7] p-5 sm:p-6"><h2 className="text-lg font-bold text-[#8d4e3e]">Privacy & data</h2><p className="mt-2 text-sm leading-6 text-[#926e62]">Export your account data, manage sensitive records, or request account deletion. Deletion requests are reviewed before an account is removed.</p><div className="mt-4 flex flex-wrap gap-3"><a href="/api/privacy/export" className="rounded-xl border border-[#ead4ca] bg-white px-4 py-3 text-sm font-bold text-[#9d5742]">Export my data</a><Link href="/account/deletion-request" className="rounded-xl bg-[#a6503d] px-4 py-3 text-sm font-bold text-white">Request account deletion</Link></div></section>
    </div></main>;
}

function Check({ name, label, checked }: { name: string; label: string; checked: boolean }) { return <label className="flex items-center justify-between gap-5 rounded-xl bg-[#f7faf7] px-4 py-3 text-sm font-semibold text-[#25443d]"><span>{label}</span><input name={name} type="checkbox" defaultChecked={checked} className="h-4 w-4 accent-[#27815b]"/></label>; }
